### ISSUE TITLE
Correções no app web

### ISSUE THREAD

**Issue by acenelio** [leodelmiro/MovieFlix#1]
Parabéns pelo trabalho Leonardo. Favor arrumar algumas coisas importantes para deixar o projeto melhor e mais apresentável:

1) Eliminar o tremido quando digita usuário e senha

2) Quando clicar no botão sair, tem que voltar para a tela de login

3) Favor mostrar o ano dos filmes, e colocar subtítulo em todos filmes do seu seed.

4) Opcional: quando o usuário entrar com uma avaliação, não mudar de tela e atualizar a listagem de avaliações na tela.

Fiz um vídeo mostrando esses pontos:
https://youtu.be/bVE2o7UkYfU

**Comment by leodelmiro** [comment]
Bom dia, Nélio. 

Obrigado, pelo retorno. Realizei as correções no commit 0da17dee5fb41fee605bd8fbe8f992100f036094

At.
Leonardo Delmiro
